version: '3'
services:
  nginx:
    build: ./nginx/
    container_name: nginx_flaskapp
    networks: 
      - app
  flaskapp:
    build: ./flaskapp/
    container_name: flaskapp
    networks:
      - app
  networks:
    app:
      external: true
      name: app
